# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SSNavigatorDemo' do
pod 'SSNavigatorFramework', :path => '../'
end

target 'SSNavigatorDemoTests' do

end

